In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('train.txt', sep=';', header=None, names=["text","emotion"])

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [ ]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:
df["emotion"].value_counts()

emotion
joy         5362
sadness     4666
anger       2159
fear        1937
love        1304
surprise     572
Name: count, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
df['emotion']=le.fit_transform(df['emotion'])

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
'''
unique_emotion=df["emotion"].unique()
emotion_numbers={
     unique_emotion[i] : i for i in range(len(unique_emotion))
}

df["emotion"]=df["emotion"].map(emotion_numbers)
'''

'\nunique_emotion=df["emotion"].unique()\nemotion_numbers={\n     unique_emotion[i] : i for i in range(len(unique_emotion))\n}\n\ndf["emotion"]=df["emotion"].map(emotion_numbers)\n'

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
df['text']=df['text'].apply(lambda x: x.lower())

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [ ]:
df['text']=df['text'].apply(remove_punc)

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
def remove_num(txt):
  new=""
  for i in txt:
    if not i.isdigit():
      new+=i
  return new

df['text']=df['text'].apply(remove_num)

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
def remove_emojis(txt):
  new=""
  for i in txt:
    if i.isascii():
      new+=i
  return new

df['text']=df['text'].apply(remove_emojis)

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
import nltk

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [ ]:
stop_words=set(stopwords.words('english'))

In [ ]:
len(stop_words)

198

In [ ]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated        4
1  i can go from feeling so hopeless to so damned...        4
2   im grabbing a minute to post i feel greedy wrong        0
3  i am ever feeling nostalgic about the fireplac...        3
4                               i am feeling grouchy        0

In [ ]:
df.loc[1]['text']

'i can go from feeling so hopeless to so damned hopeful just from being around someone who cares and is awake'

In [ ]:
def remove(txt):
  words=word_tokenize(txt)
  cleaned=[]
  for w in words:
    if w not in stop_words:
      cleaned.append(w)
  return " ".join(cleaned)

df['text']=df['text'].apply(remove)

In [ ]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        4
1  go feeling hopeless damned hopeful around some...        4
2          im grabbing minute post feel greedy wrong        0
3  ever feeling nostalgic fireplace know still pr...        3
4                                    feeling grouchy        0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

documents=[
    "I love pizza",
    "Pizza is the best",
    "I love pasta",
    "Pasta is great",
]

vectorizer=TfidfVectorizer()

x=vectorizer.fit_transform(documents)

print("Vocab", vectorizer.get_feature_names_out())
print("Bow matrix", x.toarray())

Vocab ['best' 'great' 'is' 'love' 'pasta' 'pizza' 'the']
Bow matrix [[0.         0.         0.         0.70710678 0.         0.70710678
  0.        ]
 [0.55528266 0.         0.43779123 0.         0.         0.43779123
  0.55528266]
 [0.         0.         0.         0.70710678 0.70710678 0.
  0.        ]
 [0.         0.66767854 0.52640543 0.         0.52640543 0.
  0.        ]]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

In [ ]:
X_test.shape

(3200,)

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [ ]:
bow_vectorizer=CountVectorizer()
vectorizer=TfidfVectorizer()

In [ ]:
X_train_bow=bow_vectorizer.fit_transform(X_train)
X_test_bow=bow_vectorizer.transform(X_test)

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
nb_model=MultinomialNB()
nb_model.fit(X_train_bow, y_train)

MultinomialNB()

In [ ]:
y_pred=nb_model.predict(X_test_bow)

In [ ]:
accuracy=accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.7678125

In [ ]:
y_pred

array([4, 2, 4, ..., 2, 2, 4])

In [ ]:
y_test

8756     4
4660     2
6095     4
304      2
8241     4
        ..
15578    2
5746     2
6395     2
7624     2
15245    4
Name: emotion, Length: 3200, dtype: int64

In [ ]:
X_train_tfidf=vectorizer.fit_transform(X_train)
X_test_tfidf=vectorizer.transform(X_test)

In [ ]:
model2=MultinomialNB()
model2.fit(X_train_tfidf, y_train)

MultinomialNB()

In [ ]:
y_pred=model2.predict(X_test_tfidf)

In [ ]:
accuracy=accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6609375

In [ ]:
lg_model=LogisticRegression(max_iter=1000)
lg_model.fit(X_train_tfidf, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
lg_model.fit(X_train_tfidf, y_train)
y_pred=lg_model.predict(X_test_tfidf)

In [ ]:
accuracy=accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.8615625